#cloud-config

write_files:
  - path: /etc/kubelet.kube-01.env
    permissions: '0600'
    owner: root
    content: |
      KUBELET_HOST_ARGS="--register-node=false"

  - path: /etc/kubelet.env
    permissions: '0600'
    owner: root
    content: |
      KUBELET_HOST_ARGS="--docker-endpoint=unix:/var/run/weave/weave.sock"

  - path: /etc/weave.env
    permissions: '0600'
    owner: root
    content: |
      WEAVE_PEERS="172.17.8.101 172.17.8.102 172.17.8.103"
      # Uncomment and make it more secure
      # WEAVE_PASSWORD="aVeryLongString"

  - path: "/etc/kubernetes/manifests/weave-scope.yaml"
    permissions: '0600'
    owner: root
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: weave-scope
        namespace: kube-system
      spec:
        hostNetwork: true
        hostPID: true
        containers:
        - name: scope
          image: weaveworks/scope:0.9.0
          args:
          - --probe.docker
          - "true"
          - --probe.kubernetes
          - "true"
          - 172.17.8.101
          - 172.17.8.102
          - 172.17.8.103
          ports:
          - containerPort: 4040
            hostPort: 4040
            name: local
          securityContext:
            privileged: true

  - path: "/etc/kubernetes/manifests/kube-proxy.yaml"
    permissions: '0600'
    owner: root
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-proxy
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-proxy
          image: gcr.io/google_containers/hyperkube:v1.0.6
          command:
          - /hyperkube
          - proxy
          - --master=http://172.17.8.101:8080
          - --logtostderr=true
          - --v=2
          securityContext:
            privileged: true

  - path: "/etc/kubernetes/master-manifests/kube-master.yaml"
    permissions: '0600'
    owner: root
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-master
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-apiserver
          image: gcr.io/google_containers/hyperkube:v1.0.6
          command:
          - /hyperkube
          - apiserver
          - --insecure-bind-address=0.0.0.0
          - --advertise-address=$public_ipv4
          - --port=8080
          - --etcd-servers=http://localhost:4001
          - --service-cluster-ip-range=10.16.0.0/12
          - --cloud-provider=vagrant
          - --logtostderr=true
          - --v=3
          - --allow-privileged=true
          ports:
          - containerPort: 8080
            hostPort: 8080
            name: local
        - name: kube-controller-manager
          image: gcr.io/google_containers/hyperkube:v1.0.6
          command:
          - /hyperkube
          - controller-manager
          - --master=http://localhost:8080
          - --logtostderr=true
          - --v=2
        - name: kube-scheduler
          image: gcr.io/google_containers/hyperkube:v1.0.6
          command:
          - /hyperkube
          - scheduler
          - --master=http://localhost:8080
          - --logtostderr=true
          - --v=2

coreos:
  update:
    group: stable
    reboot-strategy: 'off'

  etcd2:
    name: '$public_ipv4'
    initial-cluster-token: 'etcd-cluster'
    initial-advertise-peer-urls: 'http://$public_ipv4:2380'
    listen-peer-urls: 'http://$public_ipv4:2380'
    listen-client-urls: 'http://0.0.0.0:2379,http://0.0.0.0:4001'
    advertise-client-urls: 'http://$public_ipv4:2379,http://$public_ipv4:4001'
    initial-cluster-state: 'new'
    initial-cluster: '172.17.8.101=http://172.17.8.101:2380'
    #initial-cluster: '172.17.8.101=http://172.17.8.101:2380,172.17.8.102=http://172.17.8.102:2380,172.17.8.103=http://172.17.8.103:2380'

  units:
    - name: systemd-networkd-wait-online.service
      drop-ins:
        - name: 50-check-github-is-reachable.conf
          content: |
            [Service]
            ExecStart=/bin/sh -x -c \
              'until curl --silent --fail https://status.github.com/api/status.json | grep -q \"good\"; do sleep 2; done'

    - name: etcd2.service
      command: start

    - name: weave-network.target
      enable: true
      content: |
        [Unit]
        Description=Weave Network Setup Complete
        Documentation=man:systemd.special(7)
        RefuseManualStart=no
        After=network-online.target
        [Install]
        WantedBy=multi-user.target
        WantedBy=kubernetes-master.target
        WantedBy=kubernetes-node.target

    - name: kubernetes-master.target
      enable: true
      command: start
      content: |
        [Unit]
        Description=Kubernetes Cluster Master
        Documentation=http://kubernetes.io/
        RefuseManualStart=no
        After=weave-network.target
        Requires=weave-network.target
        ConditionHost=kube-01
        Wants=kubelet.service
        [Install]
        WantedBy=multi-user.target

    - name: kubernetes-node.target
      enable: true
      command: start
      content: |
        [Unit]
        Description=Kubernetes Cluster Node
        Documentation=http://kubernetes.io/
        RefuseManualStart=no
        After=weave-network.target
        Requires=weave-network.target
        ConditionHost=!kube-01
        Wants=kubelet.service
        [Install]
        WantedBy=multi-user.target

    - name: 10-weave.network
      runtime: false
      content: |
        [Match]
        Type=bridge
        Name=weave*
        [Network]

    - name: install-weave.service
      enable: true
      content: |
        [Unit]
        After=network-online.target
        After=docker.service
        Before=weave.service
        Description=Install Weave
        Documentation=http://docs.weave.works/
        Requires=network-online.target
        [Service]
        EnvironmentFile=-/etc/weave.%H.env
        EnvironmentFile=-/etc/weave.env
        Type=oneshot
        RemainAfterExit=yes
        TimeoutStartSec=0
        ExecStartPre=/bin/mkdir -p /opt/bin/
        ExecStartPre=/usr/bin/curl \
          --silent \
          --location \
          git.io/weave \
          --output /opt/bin/weave
        ExecStartPre=/usr/bin/chmod +x /opt/bin/weave
        ExecStart=/opt/bin/weave setup
        [Install]
        WantedBy=weave-network.target
        WantedBy=weave.service

    - name: weaveproxy.service
      enable: true
      content: |
        [Unit]
        After=install-weave.service
        After=docker.service
        Description=Weave proxy for Docker API
        Documentation=http://docs.weave.works/
        Requires=docker.service
        Requires=install-weave.service
        [Service]
        EnvironmentFile=-/etc/weave.%H.env
        EnvironmentFile=-/etc/weave.env
        Environment=WEAVE_DEBUG=1
        ExecStartPre=/opt/bin/weave launch-proxy \
          --rewrite-inspect $HOSNAME_EXPRESSION_ARGS
        ExecStart=/usr/bin/docker attach weaveproxy
        Restart=on-failure
        ExecStop=/opt/bin/weave stop-proxy
        [Install]
        WantedBy=weave-network.target

    - name: weave.service
      enable: true
      content: |
        [Unit]
        After=install-weave.service
        After=docker.service
        Description=Weave Network Router
        Documentation=http://docs.weave.works/
        Requires=docker.service
        Requires=install-weave.service
        [Service]
        TimeoutStartSec=0
        EnvironmentFile=-/etc/weave.%H.env
        EnvironmentFile=-/etc/weave.env
        ExecStartPre=/opt/bin/weave launch-router $WEAVE_PEERS
        ExecStart=/usr/bin/docker attach weave
        Restart=on-failure
        ExecStop=/opt/bin/weave stop-router
        [Install]
        WantedBy=weave-network.target

    - name: weave-expose.service
      enable: true
      content: |
        [Unit]
        After=install-weave.service
        After=weave.service
        After=docker.service
        Documentation=http://docs.weave.works/
        Requires=docker.service
        Requires=install-weave.service
        Requires=weave.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        TimeoutStartSec=0
        EnvironmentFile=-/etc/weave.%H.env
        EnvironmentFile=-/etc/weave.env
        ExecStart=/opt/bin/weave expose
        ExecStop=/opt/bin/weave hide
        [Install]
        WantedBy=weave-network.target

    - name: kubelet.service
      enable: true
      content: |
        [Unit]
        After=weave-network.target
        ConditionFileIsExecutable=/usr/bin/kubelet
        Description=Kubernetes Kubelet
        Documentation=http://kubernetes.io/
        Wants=weave-network.target
        [Service]
        EnvironmentFile=-/etc/kubelet.env
        EnvironmentFile=-/etc/kubelet.%H.env
        ExecStartPre=-/bin/bash -c \
          'test %H = kube-01 && cp /etc/kubernetes/master-manifests/kube-master.yaml /etc/kubernetes/manifests/'
        ExecStart=/usr/bin/kubelet \
            $KUBELET_HOST_ARGS \
            --api-servers=http://172.17.8.101:8080 \
            --config=/etc/kubernetes/manifests/ \
            --port=10250 \
            --logtostderr=true \
            --allow-privileged=true \
            --v=2
        Restart=always
        RestartSec=10
        [Install]
        WantedBy=kubernetes-node.target
